[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.mysqli",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "nginx",
  "gettext"
]

[phases.build]
cmds = [
  "echo 'extension=mysqli' >> $(php --ini | grep 'Loaded Configuration' | sed 's/.*: //')",
  "echo 'extension=pdo_mysql' >> $(php --ini | grep 'Loaded Configuration' | sed 's/.*: //')"
]

[start]
cmd = "bash /app/start.sh"
