[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mysqli",
  "php82Extensions.mbstring",
  "php82Extensions.gd",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Extensions.intl",
  "nginx"
]

[phases.build]
cmds = ["mkdir -p /var/run/php /var/log/nginx"]

[start]
cmd = "php-fpm82 -D && nginx -g 'daemon off;'"
